apiVersion: batch/v1
kind: Job
metadata:
  name: clsrmsch-job
spec:
  template:
    spec:
      containers:
      - name: clsrmsch-job
        image: yash5090/clsrmsch:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
