apiVersion: apps/v1
kind: Deployment
metadata:
  name: clsrmsch-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: clsrmsch
  template:
    metadata:
      labels:
        app: clsrmsch
    spec:
      containers:
        - name: clsrmsch
          image: yash5090/clsrmsch:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
